# Generated by Django 5.0.7 on 2024-08-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_branch_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
