# Generated by Django 5.0.7 on 2024-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_model_type_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
